# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        environment:
          ENV: UnitTest
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - pip-cache-{{ .Branch }}
            - pip-cache

      - run:
          name: install dependencies
          command: |
            virtualenv --no-site-packages .
            source bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
      - save_cache:
          key: pip-cache-{{ .Branch }}
          paths:
            - "../.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
      - save_cache:
          key: pip-cache
          paths:
            - "../.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"

      - run:
          name: Set up DB
          command: |
            source bin/activate
            python db_migration_repo/manage.py version_control
            python db_migration_repo/manage.py db_version
            python db_migration_repo/manage.py version
            python db_migration_repo/manage.py upgrade

      - run:
          name: run tests
          command: |
            source bin/activate
            python run_test.py ut
            coverage run run_test.py ut
            coverage html --include=test/* --directory=reports/coverage

      - store_artifacts:
          path: reports
          destination: reports

      - run:
          name: setup heroku
          command: |
            bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "95:70:6d:55:34:41:75:09:2a:80:ea:ca:63:a6:40:3c"

      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku run python db_migration_repo/manage.py upgrade
              heroku run python manage.py deploy
              heroku restart
            fi
