# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        environment:
          ENV: UnitTest
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - pip-cache-{{ .Branch }}
            - pip-cache

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt --user

      - save_cache:
          key: pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python2.7/site-packages/
      - save_cache:
          key: pip-cache-{{ .Branch }}
          paths:
            - /usr/local/lib/python2.7/site-packages/
      - save_cache:
          key: pip-cache
          paths:
            - /usr/local/lib/python2.7/site-packages/

      - run:
          name: Set up DB
          command: |
            python db_maigration_repo/manage.py version_control
            python db_maigration_repo/manage.py db_version
            python db_maigration_repo/manage.py version
            python db_maigration_repo/manage.py upgrade

      - run:
          name: run tests
          command: |
            python run_test.py ut

      - store_artifacts:
          path: test-reports
          destination: test-reports
