# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        environment:
          ENV: UnitTest
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - pip-cache-{{ .Branch }}
            - pip-cache

      - run:
          name: install dependencies
          command: |
            virtualenv --no-site-packages .
            source bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: pip-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
      - save_cache:
          key: pip-cache-{{ .Branch }}
          paths:
            - "../.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
      - save_cache:
          key: pip-cache
          paths:
            - "../.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"

      - run:
          name: Set up DB
          command: |
            source bin/activate
            python db_maigration_repo/manage.py version_control
            python db_maigration_repo/manage.py db_version
            python db_maigration_repo/manage.py version
            python db_maigration_repo/manage.py upgrade

      - run:
          name: run tests
          command: |
            source bin/activate
            python run_test.py ut
            coverage run run_test.py ut
            coverage html --include=test/* --directory=test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
